version: '3.7'

services:

  db:
    image: 'postgres:12.2-alpine'
    hostname: "${POSTGRES_HOSTNAME}"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: postgres -c config_file=/etc/postgresql.conf -c hba_file=/etc/pg_hba.conf
    volumes:
      # - ~/data/OKMaps/${COMPOSE_PROJECT_NAME}/postgresql/data:/var/lib/postgresql/data
      - db_data:/var/lib/postgresql/data
      - ./server/workers/pg_hba.conf:/etc/pg_hba.conf
      - ./server/workers/postgresql.conf:/etc/postgresql.conf
    networks: 
      - headstart

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '127.0.0.1:54323:80'
    networks:
      - headstart

  redis:
    image: 'redis:6.0-alpine'
    restart: always
    hostname: "${REDIS_HOST}"
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
    command: ["redis-server", "/etc/redis/redis.conf", "--bind", "${REDIS_HOST}", "--appendonly", "yes", "--port", "${REDIS_PORT}"]
    volumes:
        - 'redis:/var/lib/redis/data'
        - ./server/workers/redis.conf:/etc/redis/redis.conf
        - ./server/workers/certs:/etc/certs
    ports:
     - "127.0.0.1:${REDIS_PORT}:6379"
    restart: always
    networks: 
      - headstart

  api:
    image: api:${SERVICE_VERSION}
    restart: always
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_SSL: "${REDIS_SSL}"
      BEHIND_PROXY: "${BEHIND_PROXY}"
      DEFAULT_DATABASE: "${DEFAULT_DATABASE}"
      DATABASES: "${DATABASES}"
      FLASK_ENV: "${FLASK_ENV}"
    command: ["gunicorn",  "--workers", "10", "--threads", "2", "-b", "0.0.0.0:${API_PORT}", "app:app", "--timeout", "300"]
    depends_on:
      - redis
    networks: 
      - headstart

  persistence:
    image: persistence:${SERVICE_VERSION}
    restart: always
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      BEHIND_PROXY: "${BEHIND_PROXY}"
      DEFAULT_DATABASE: "${DEFAULT_DATABASE}"
      DATABASES: "${DATABASES}"
      FLASK_ENV: "${FLASK_ENV}"
    command: ["gunicorn",  "--workers", "10", "--threads", "2", "-b", "0.0.0.0:${API_PORT}", "app:app", "--timeout", "300"]
    networks: 
      - headstart

  triple:
    image: triple:${SERVICE_VERSION}
    env_file:
      - server/workers/triple/triple.env
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_SSL: "${REDIS_SSL}"
      LOGLEVEL: "${LOGLEVEL}"
      TRIPLE_USER: "${TRIPLE_USER}"
      TRIPLE_PASS: "${TRIPLE_PASS}"
      TRIPLE_HOST: "${TRIPLE_HOST}"
      TRIPLE_PORT: "${TRIPLE_PORT}"
      TRIPLE_DOCUMENTS_INDEX: "${TRIPLE_DOCUMENTS_INDEX}"
      TRIPLE_PROJECTS_INDEX: "${TRIPLE_PROJECTS_INDEX}"
      TRIPLE_AUTHORS_INDEX: "${TRIPLE_AUTHORS_INDEX}"
    restart: always
    depends_on:
      - redis
    networks: 
      - headstart

  gsheets:
    image: gsheets:${SERVICE_VERSION}
    env_file:
      - server/workers/gsheets/gsheets.env
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_SSL: "${REDIS_SSL}"
      LOGLEVEL: "${LOGLEVEL}"
    restart: always
    depends_on:
      - redis
    networks: 
      - headstart

  dataprocessing:
    image: dataprocessing:${SERVICE_VERSION}
    env_file:
    - server/workers/dataprocessing/dataprocessing.env
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_SSL: "${REDIS_SSL}"
      LOGLEVEL: "${LOGLEVEL}"
    restart: always
    volumes:
      - /opt/local/renv/cache:/renv/cache
      - /var/log/headstart:/var/log/headstart
    depends_on:
      - redis
    networks: 
      - headstart

  base:
    image: base:${SERVICE_VERSION}
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_SSL: "${REDIS_SSL}"
      LOGLEVEL: "${LOGLEVEL}"
      LOGFILE: "/var/log/headstart/headstart.log"
      RENV_VERSION: 0.14.0-5
      CRAN_REPOS: https://cran.wu.ac.at
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      RENV_PATHS_CACHE: /renv/cache
      PYTHONIOENCODING: "utf-8"
    restart: always
    volumes:
      - /opt/local/renv/cache:/renv/cache
      - /var/log/headstart:/var/log/headstart
    depends_on:
      - redis
    networks:
      - headstart

  pubmed:
    image: pubmed:${SERVICE_VERSION}
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_SSL: "${REDIS_SSL}"
      LOGLEVEL: "${LOGLEVEL}"
      LOGFILE: "/var/log/headstart/headstart.log"
      RENV_VERSION: 0.14.0-5
      CRAN_REPOS: https://cran.wu.ac.at
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      RENV_PATHS_CACHE: /renv/cache
      PYTHONIOENCODING: "utf-8"
    restart: always
    volumes:
      - /opt/local/renv/cache:/renv/cache
      - /var/log/headstart:/var/log/headstart
    depends_on:
      - redis
    networks:
      - headstart

  openaire:
    image: openaire:${SERVICE_VERSION}
    environment:
      SERVICE_VERSION: "${SERVICE_VERSION}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_SSL: "${REDIS_SSL}"
      LOGLEVEL: "${LOGLEVEL}"
      LOGFILE: "/var/log/headstart/headstart.log"
      RENV_VERSION: 0.14.0-5
      CRAN_REPOS: https://cran.wu.ac.at
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      RENV_PATHS_CACHE: /renv/cache
      PYTHONIOENCODING: "utf-8"
    restart: always
    volumes:
      - /opt/local/renv/cache:/renv/cache
      - /var/log/headstart:/var/log/headstart
    depends_on:
      - redis
    networks:
      - headstart

volumes:
  redis:
  db_data:
    driver: local

networks:
  headstart: