version: '3.7'

services:

  redis:
    image: 'redis:4.0-alpine'
    restart: always
    command: redis-server
    volumes:
       - 'redis:/var/lib/redis/data'
    restart: always
    ports:
      - '6379:6379'

  search_triple:
    build:
      context: server
      dockerfile: search_triple.docker
    restart: always

  backend:
    build:
      context: server
      dockerfile: headstart_backend.docker
    env_file:
      - server/workers/backend/backend.env
    restart: always
    ports:
      - '8019:8019'

volumes:
  redis:
